# Site settings
title: Test Blog
description: A blog about tasty food, technology and other stuff.
baseurl: "/blog-test"
url: "https://arminha.github.io"

# Build settings
markdown:    kramdown
highlighter: pygments
permalink:   pretty

paginate:    5

# Octopress settings
post_ext: md
