# Site settings
title: A Bowl of Spaghetti Code
description: On tasty food, technology and other stuff.
baseurl: "/spaghetticode"
url: "https://arminha.github.io"

# Build settings
markdown:    kramdown
highlighter: pygments
permalink:   pretty

paginate:    5

# compress HTML settings
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  ignore:
    envs: [local]

# Octopress settings
post_ext: md
