# Basics
title = "A Bowl of Spaghetti Code"
base_url = "https://arminha.github.io/spaghetticode/"
compile_sass = true
highlight_code = false
build_search_index = false

# Feed
generate_feed = true
feed_filename = "atom.xml"

taxonomies = [ { name = "categories" } ]

[link_checker]
skip_anchor_prefixes = [
  "https://github.com/shadowsocks/",
]

[extra]
copyright_year = 2020
